Add validation of id parameter in getCommit method of BitBucket client
octopusden/octopus-external-systems-client pull request #28
Opened 2023-10-12 12:48 UTC by CamaradeRoman

resolves #25

2023-10-12 13:03 UTC, aryabokon commented on bitbucket-client/src/main/kotlin/org/octopusden/octopus/infrastructure/bitbucket/client/BitbucketCommitIdValidator.kt
> +        val commitIdRegex = "[0-9a-fA-F]+".toRegex()
```suggest
private val commitIdRegex = "[0-9a-fA-F]+".toRegex()
```

2023-10-12 13:03 UTC, aryabokon submitted a review, later dismissed

2023-10-12 14:28 UTC, pgorbachev requested changes

2023-10-12 14:28 UTC, pgorbachev commented on bitbucket-client/src/main/kotlin/org/octopusden/octopus/infrastructure/bitbucket/client/BitbucketCommitIdValidator.kt
> +        private val commitIdRegex = "[0-9a-fA-F]+".toRegex()
I propose to follow UPPER_CASE rule for constants i.e. COMMIT_ID_REGEX

2023-10-13 07:13 UTC, fishinitself approved these changes

2023-10-13 07:22 UTC, ozonophore approved these changes

2023-10-13 09:06 UTC, pgorbachev approved these changes

2023-10-13 10:30 UTC, merged