Add raising an exception in the method 'wait'
octopusden/octopus-external-systems-client pull request #36
Opened 2023-12-01 14:37 UTC by ozonophore

2023-12-01 15:07 UTC, pgorbachev requested changes

2023-12-01 15:07 UTC, pgorbachev commented on test-client-commons/src/main/kotlin/org/octopusden/octopus/infrastructure/common/test/BaseTestClient.kt
> +            throw IllegalStateException("Wait failed", exception)
@ozonophore 
Давай тут напишем, что "Git Server Issue. Commit <> is not reflected in repository <> within the <> seconds"

2023-12-01 15:12 UTC, CamaradeRoman commented on test-client-commons/src/main/kotlin/org/octopusden/octopus/infrastructure/common/test/BaseTestClient.kt
> +    private fun wait(retries: Int = 20, pingIntervalMsec: Long = 500, raiseOnException: Boolean = false, waitMessage: String, checkFunc: () -> Unit) {
Нужно на все вызовы wait передавать одинаковые значения из свойств класса, включая https://github.com/octopusden/octopus-external-systems-client/blob/ac9947b26ac2f5ef453348abe869c6344c82fce1/test-client-commons/src/main/kotlin/org/octopusden/octopus/infrastructure/common/test/BaseTestClient.kt#L55

И соответственно - стоит убрать дефолты из параметров метода.

2023-12-01 15:35 UTC, ozonophore commented on test-client-commons/src/main/kotlin/org/octopusden/octopus/infrastructure/common/test/BaseTestClient.kt
> +    private fun wait(retries: Int = 20, pingIntervalMsec: Long = 500, raiseOnException: Boolean = false, waitMessage: String, checkFunc: () -> Unit) {
поправил

2023-12-01 16:12 UTC, pgorbachev requested changes

2023-12-01 16:12 UTC, pgorbachev commented on test-client-commons/src/main/kotlin/org/octopusden/octopus/infrastructure/common/test/BaseTestClient.kt
> +            throw IllegalStateException("Wait failed", exception)
Предлагаю добавить что-нибудь, проясняющее к какой системе относится проблема.
Git Server Issue и/или Commit wasn't published, чтобы сразу было понимание к чему относится эксепшен

2023-12-01 16:41 UTC, pgorbachev commented on settings.gradle.kts
> -include("gitlab-test-client")
@CamaradeRoman , я за то чтобы максимально остаться в рамках текущей постановки задачи. 
тесты мы выключить хотим, т.к. они сейчас могут падать? если так - то давайте только их выключим, если они проходят, то можно было бы вообще не трогать.
Гитлаб если решим выкинуть, лучше отдельной задачей сделать

2023-12-01 17:03 UTC, CamaradeRoman commented on settings.gradle.kts
> -include("gitlab-test-client")
@pgorbachev нестабильно ведёт себя один тест на gitlab на создание pr. Хотелось только отключить тесты.

2023-12-01 17:28 UTC, ozonophore commented on test-client-commons/src/main/kotlin/org/octopusden/octopus/infrastructure/common/test/BaseTestClient.kt
> +            throw IllegalStateException("Wait failed", exception)
Нельзя там добавить ни commit ни issue тк wait абстрактный и не привязан к этим параметрам. Внитри может быть запущена любая задача не привязанная к коммиту и вообще к гиту

2023-12-01 17:49 UTC, CamaradeRoman commented on test-client-commons/src/main/kotlin/org/octopusden/octopus/infrastructure/common/test/BaseTestClient.kt
> +            throw IllegalStateException("Wait failed", exception)
@ozonophore есть параметр waitMessage, почему нельзя добавить параметр, failMessage или что-то подобное?

2023-12-01 19:37 UTC, ozonophore commented on test-client-commons/src/main/kotlin/org/octopusden/octopus/infrastructure/common/test/BaseTestClient.kt
> +            throw IllegalStateException("Wait failed", exception)
Добавил

2023-12-04 10:23 UTC, ozonophore commented on test-client-commons/src/main/kotlin/org/octopusden/octopus/infrastructure/common/test/BaseTestClient.kt
> +    override fun commit(newChangeSet: NewChangeSet, parent: String?, commitExceptionMessage: String?): ChangeSet {
убрал

2023-12-04 11:32 UTC, pgorbachev approved these changes

2023-12-04 12:31 UTC, CamaradeRoman approved these changes

2023-12-04 12:52 UTC, merged