Support retry operation in testTag()
octopusden/octopus-external-systems-client pull request #71
Opened 2024-10-16 03:49 UTC by adellinekania

Enhance the `deleteTag()` function within `testTag()` to include a retry mechanism with delays. This is to address the intermittent failure caused by a “NotFoundException: The target couldn’t be found” in the `GiteaTestClient`.

2024-10-16 04:04 UTC, fishinitself commented on test-client-test-commons/src/main/kotlin/org/octopusden/octopus/infrastructure/common/util/RetryOperation.kt
> +    var attempts: Int = 0
I didn't catch where attempts (is it maximum amount of attempts, right) is set?

2024-10-17 08:36 UTC, pgorbachev requested changes
check comments

2024-10-21 07:01 UTC, ozonophore commented on gitea-test-client/src/test/kotlin/org/octopusden/octopus/infrastructure/gitea/test/GiteaTestClientTest.kt
> +    private val _log: Logger = LoggerFactory.getLogger(GiteaTestClientTest::class.java)
I doubt that naming constants starting with an underscore is correct.

2024-10-21 07:02 UTC, ozonophore commented on gitea-test-client/src/test/kotlin/org/octopusden/octopus/infrastructure/gitea/test/GiteaTestClientTest.kt
> +                _log.warn(message)
log.warn(message, e)

2024-10-21 08:50 UTC, pgorbachev commented on gitea-test-client/src/test/kotlin/org/octopusden/octopus/infrastructure/gitea/test/GiteaTestClientTest.kt
> +private const val RETRY_INTERVAL_SEC: Long = 60
I guess it should be much shorter (1sec?)

2024-10-22 08:55 UTC, pgorbachev requested changes
Let's use full version of RetryOperation.kt from releng

2024-10-22 09:53 UTC, pgorbachev approved these changes

2024-10-28 07:46 UTC, pgorbachev approved these changes

2024-10-28 11:20 UTC, aryabokon approved these changes

2024-10-29 01:29 UTC, merged